// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitiatePaymentRq struct {
	ApplicationId    string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	MerchantId       string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SubApplicationId string `protobuf:"bytes,3,opt,name=sub_application_id,json=subApplicationId,proto3" json:"sub_application_id,omitempty"`
	SubMerchantId    string `protobuf:"bytes,4,opt,name=sub_merchant_id,json=subMerchantId,proto3" json:"sub_merchant_id,omitempty"`
	DeviceId         string `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Unique transaction reference id, random string of 32
	TransactionRefId string `protobuf:"bytes,6,opt,name=transaction_ref_id,json=transactionRefId,proto3" json:"transaction_ref_id,omitempty"`
	Description      string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Version          string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	// Json data serialized (blob)
	ItemDetails string `protobuf:"bytes,9,opt,name=item_details,json=itemDetails,proto3" json:"item_details,omitempty"`
	// Json data serialized (blob)
	InvoiceDetails      string `protobuf:"bytes,10,opt,name=invoice_details,json=invoiceDetails,proto3" json:"invoice_details,omitempty"`
	AdditionalData      string `protobuf:"bytes,11,opt,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty"`
	MerchantOrderNumber string `protobuf:"bytes,12,opt,name=merchant_order_number,json=merchantOrderNumber,proto3" json:"merchant_order_number,omitempty"`
	PaymentAmount       int64  `protobuf:"varint,13,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	CurrencyCode        string `protobuf:"bytes,14,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	TerminalIpAddress   string `protobuf:"bytes,15,opt,name=terminal_ip_address,json=terminalIpAddress,proto3" json:"terminal_ip_address,omitempty"`
	// Bar code/QR code
	AuthorizationCode string `protobuf:"bytes,16,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	// payment request will be valid (usable) between start_time and
	// end_time set in UTC. Attempts to use a user payment option to make a
	// booking outside of this interval will fail. (both optional)
	ValidStartTime       *timestamp.Timestamp `protobuf:"bytes,17,opt,name=valid_start_time,json=validStartTime,proto3" json:"valid_start_time,omitempty"`
	ValidEndTime         *timestamp.Timestamp `protobuf:"bytes,18,opt,name=valid_end_time,json=validEndTime,proto3" json:"valid_end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InitiatePaymentRq) Reset()         { *m = InitiatePaymentRq{} }
func (m *InitiatePaymentRq) String() string { return proto.CompactTextString(m) }
func (*InitiatePaymentRq) ProtoMessage()    {}
func (*InitiatePaymentRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *InitiatePaymentRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiatePaymentRq.Unmarshal(m, b)
}
func (m *InitiatePaymentRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiatePaymentRq.Marshal(b, m, deterministic)
}
func (m *InitiatePaymentRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiatePaymentRq.Merge(m, src)
}
func (m *InitiatePaymentRq) XXX_Size() int {
	return xxx_messageInfo_InitiatePaymentRq.Size(m)
}
func (m *InitiatePaymentRq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiatePaymentRq.DiscardUnknown(m)
}

var xxx_messageInfo_InitiatePaymentRq proto.InternalMessageInfo

func (m *InitiatePaymentRq) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *InitiatePaymentRq) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *InitiatePaymentRq) GetSubApplicationId() string {
	if m != nil {
		return m.SubApplicationId
	}
	return ""
}

func (m *InitiatePaymentRq) GetSubMerchantId() string {
	if m != nil {
		return m.SubMerchantId
	}
	return ""
}

func (m *InitiatePaymentRq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *InitiatePaymentRq) GetTransactionRefId() string {
	if m != nil {
		return m.TransactionRefId
	}
	return ""
}

func (m *InitiatePaymentRq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InitiatePaymentRq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *InitiatePaymentRq) GetItemDetails() string {
	if m != nil {
		return m.ItemDetails
	}
	return ""
}

func (m *InitiatePaymentRq) GetInvoiceDetails() string {
	if m != nil {
		return m.InvoiceDetails
	}
	return ""
}

func (m *InitiatePaymentRq) GetAdditionalData() string {
	if m != nil {
		return m.AdditionalData
	}
	return ""
}

func (m *InitiatePaymentRq) GetMerchantOrderNumber() string {
	if m != nil {
		return m.MerchantOrderNumber
	}
	return ""
}

func (m *InitiatePaymentRq) GetPaymentAmount() int64 {
	if m != nil {
		return m.PaymentAmount
	}
	return 0
}

func (m *InitiatePaymentRq) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *InitiatePaymentRq) GetTerminalIpAddress() string {
	if m != nil {
		return m.TerminalIpAddress
	}
	return ""
}

func (m *InitiatePaymentRq) GetAuthorizationCode() string {
	if m != nil {
		return m.AuthorizationCode
	}
	return ""
}

func (m *InitiatePaymentRq) GetValidStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.ValidStartTime
	}
	return nil
}

func (m *InitiatePaymentRq) GetValidEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.ValidEndTime
	}
	return nil
}

type InitiatePaymentRs struct {
	TransactionRefId     string   `protobuf:"bytes,1,opt,name=transaction_ref_id,json=transactionRefId,proto3" json:"transaction_ref_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiatePaymentRs) Reset()         { *m = InitiatePaymentRs{} }
func (m *InitiatePaymentRs) String() string { return proto.CompactTextString(m) }
func (*InitiatePaymentRs) ProtoMessage()    {}
func (*InitiatePaymentRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *InitiatePaymentRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiatePaymentRs.Unmarshal(m, b)
}
func (m *InitiatePaymentRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiatePaymentRs.Marshal(b, m, deterministic)
}
func (m *InitiatePaymentRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiatePaymentRs.Merge(m, src)
}
func (m *InitiatePaymentRs) XXX_Size() int {
	return xxx_messageInfo_InitiatePaymentRs.Size(m)
}
func (m *InitiatePaymentRs) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiatePaymentRs.DiscardUnknown(m)
}

var xxx_messageInfo_InitiatePaymentRs proto.InternalMessageInfo

func (m *InitiatePaymentRs) GetTransactionRefId() string {
	if m != nil {
		return m.TransactionRefId
	}
	return ""
}

func (m *InitiatePaymentRs) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetPaymentRq struct {
	TransactionRefId     string   `protobuf:"bytes,1,opt,name=transaction_ref_id,json=transactionRefId,proto3" json:"transaction_ref_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentRq) Reset()         { *m = GetPaymentRq{} }
func (m *GetPaymentRq) String() string { return proto.CompactTextString(m) }
func (*GetPaymentRq) ProtoMessage()    {}
func (*GetPaymentRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{2}
}

func (m *GetPaymentRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentRq.Unmarshal(m, b)
}
func (m *GetPaymentRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentRq.Marshal(b, m, deterministic)
}
func (m *GetPaymentRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentRq.Merge(m, src)
}
func (m *GetPaymentRq) XXX_Size() int {
	return xxx_messageInfo_GetPaymentRq.Size(m)
}
func (m *GetPaymentRq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentRq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentRq proto.InternalMessageInfo

func (m *GetPaymentRq) GetTransactionRefId() string {
	if m != nil {
		return m.TransactionRefId
	}
	return ""
}

type GetPaymentRs struct {
	TransactionRefId     string   `protobuf:"bytes,1,opt,name=transaction_ref_id,json=transactionRefId,proto3" json:"transaction_ref_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaymentRs) Reset()         { *m = GetPaymentRs{} }
func (m *GetPaymentRs) String() string { return proto.CompactTextString(m) }
func (*GetPaymentRs) ProtoMessage()    {}
func (*GetPaymentRs) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{3}
}

func (m *GetPaymentRs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaymentRs.Unmarshal(m, b)
}
func (m *GetPaymentRs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaymentRs.Marshal(b, m, deterministic)
}
func (m *GetPaymentRs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaymentRs.Merge(m, src)
}
func (m *GetPaymentRs) XXX_Size() int {
	return xxx_messageInfo_GetPaymentRs.Size(m)
}
func (m *GetPaymentRs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaymentRs.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaymentRs proto.InternalMessageInfo

func (m *GetPaymentRs) GetTransactionRefId() string {
	if m != nil {
		return m.TransactionRefId
	}
	return ""
}

func (m *GetPaymentRs) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*InitiatePaymentRq)(nil), "pb.InitiatePaymentRq")
	proto.RegisterType((*InitiatePaymentRs)(nil), "pb.InitiatePaymentRs")
	proto.RegisterType((*GetPaymentRq)(nil), "pb.GetPaymentRq")
	proto.RegisterType((*GetPaymentRs)(nil), "pb.GetPaymentRs")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x18, 0xc5, 0x95, 0x0d, 0xba, 0xed, 0xeb, 0x7f, 0x4f, 0x1b, 0x51, 0x99, 0xb4, 0x12, 0x04, 0x4c,
	0x13, 0xa4, 0xd2, 0xb8, 0x9b, 0xb8, 0x60, 0x62, 0x08, 0xf5, 0x82, 0x3f, 0xea, 0x76, 0xc3, 0x05,
	0x8a, 0x9c, 0xf8, 0xdb, 0x66, 0xa9, 0xb1, 0x83, 0xed, 0x54, 0x1a, 0x97, 0xbc, 0x02, 0x3c, 0x0d,
	0xaf, 0xc1, 0x2b, 0xf0, 0x20, 0xc8, 0x76, 0xb2, 0x76, 0x1d, 0x13, 0x42, 0xe2, 0x32, 0xe7, 0xfc,
	0x7c, 0x3e, 0xd7, 0x3e, 0x2e, 0xb4, 0x0b, 0x7a, 0x99, 0xa3, 0x30, 0x71, 0xa1, 0xa4, 0x91, 0x64,
	0xa5, 0x48, 0x07, 0xbb, 0xe7, 0x52, 0x9e, 0x4f, 0x71, 0xe4, 0x94, 0xb4, 0x3c, 0x1b, 0x19, 0x9e,
	0xa3, 0x36, 0x34, 0x2f, 0x3c, 0x34, 0xd8, 0xa9, 0x00, 0x5a, 0xf0, 0x11, 0x15, 0x42, 0x1a, 0x6a,
	0xb8, 0x14, 0xda, 0xbb, 0xd1, 0xf7, 0x06, 0xf4, 0xc7, 0x82, 0x1b, 0x4e, 0x0d, 0x7e, 0xf0, 0xe1,
	0x93, 0xcf, 0xe4, 0x11, 0x74, 0x68, 0x51, 0x4c, 0x79, 0xe6, 0xd8, 0x84, 0xb3, 0x30, 0x18, 0x06,
	0x7b, 0x1b, 0x93, 0xf6, 0x82, 0x3a, 0x66, 0x64, 0x17, 0x9a, 0x39, 0xaa, 0xec, 0x82, 0x0a, 0x63,
	0x99, 0x15, 0xc7, 0x40, 0x2d, 0x8d, 0x19, 0x79, 0x0a, 0x44, 0x97, 0x69, 0xb2, 0x94, 0xb5, 0xea,
	0xb8, 0x9e, 0x2e, 0xd3, 0xa3, 0x6b, 0x71, 0x8f, 0xa1, 0x6b, 0xe9, 0xc5, 0xc8, 0x3b, 0x7e, 0xac,
	0x2e, 0xd3, 0xb7, 0xf3, 0xd4, 0xfb, 0xb0, 0xc1, 0x70, 0xc6, 0x33, 0xb4, 0xc4, 0x5d, 0x47, 0xac,
	0x7b, 0xc1, 0x8f, 0x34, 0x8a, 0x0a, 0x4d, 0x33, 0x37, 0x4e, 0xe1, 0x99, 0xa5, 0x1a, 0x7e, 0xe4,
	0x82, 0x33, 0xc1, 0xb3, 0x31, 0x23, 0x43, 0x68, 0x32, 0xd4, 0x99, 0xe2, 0x85, 0xd5, 0xc2, 0x35,
	0x87, 0x2d, 0x4a, 0x24, 0x84, 0xb5, 0x19, 0x2a, 0x6d, 0xdd, 0x75, 0xe7, 0xd6, 0x9f, 0xe4, 0x01,
	0xb4, 0xb8, 0xc1, 0x3c, 0x61, 0x68, 0x28, 0x9f, 0xea, 0x70, 0xc3, 0x2f, 0xb6, 0xda, 0xb1, 0x97,
	0xc8, 0x13, 0xe8, 0x72, 0x31, 0x93, 0x76, 0xab, 0x35, 0x05, 0x8e, 0xea, 0x54, 0xf2, 0x02, 0x48,
	0x19, 0xe3, 0x76, 0x22, 0x9d, 0x26, 0x8c, 0x1a, 0x1a, 0x36, 0x3d, 0x38, 0x97, 0x8f, 0xa9, 0xa1,
	0xe4, 0x00, 0xb6, 0xae, 0xce, 0x47, 0x2a, 0x86, 0x2a, 0x11, 0x65, 0x9e, 0xa2, 0x0a, 0x5b, 0x0e,
	0xdf, 0xac, 0xcd, 0xf7, 0xd6, 0x7b, 0xe7, 0x2c, 0x7b, 0x9b, 0x55, 0x6f, 0x12, 0x9a, 0xcb, 0x52,
	0x98, 0xb0, 0x3d, 0x0c, 0xf6, 0x56, 0x27, 0x75, 0x9b, 0x8e, 0x9c, 0x48, 0x1e, 0x42, 0x3b, 0x2b,
	0x95, 0x42, 0x91, 0x5d, 0x26, 0x99, 0x64, 0x18, 0x76, 0x5c, 0x64, 0xab, 0x16, 0x5f, 0x49, 0x86,
	0x24, 0x86, 0x4d, 0x83, 0x2a, 0xe7, 0x76, 0x9b, 0xbc, 0x48, 0x28, 0x63, 0x0a, 0xb5, 0x0e, 0xbb,
	0x0e, 0xed, 0xd7, 0xd6, 0xb8, 0x38, 0xf2, 0x06, 0x79, 0x06, 0x84, 0x96, 0xe6, 0x42, 0x2a, 0xfe,
	0xc5, 0xdf, 0xbf, 0x4b, 0xee, 0x79, 0xfc, 0x9a, 0xe3, 0xe2, 0x8f, 0xa1, 0x37, 0xa3, 0x53, 0xce,
	0x12, 0x6d, 0xa8, 0x32, 0x89, 0xed, 0x72, 0xd8, 0x1f, 0x06, 0x7b, 0xcd, 0x83, 0x41, 0xec, 0x7b,
	0x1c, 0xd7, 0x45, 0x8f, 0x4f, 0xeb, 0xa2, 0x4f, 0x3a, 0x6e, 0xcd, 0x89, 0x5d, 0x62, 0x45, 0xf2,
	0x12, 0xbc, 0x92, 0xa0, 0x60, 0x3e, 0x83, 0xfc, 0x35, 0xa3, 0xe5, 0x56, 0xbc, 0x16, 0xcc, 0x4a,
	0xd1, 0xc7, 0x9b, 0xaf, 0x42, 0xdf, 0x52, 0xad, 0xe0, 0x96, 0x6a, 0x6d, 0x43, 0x43, 0x1b, 0x6a,
	0x4a, 0x5d, 0xbd, 0x8b, 0xea, 0x2b, 0x7a, 0x01, 0xad, 0x37, 0x68, 0xe6, 0x6f, 0xed, 0x9f, 0x52,
	0xa3, 0xd3, 0x6b, 0xab, 0xff, 0xd3, 0x9e, 0x0e, 0x7e, 0x04, 0xd0, 0xa9, 0x32, 0x4f, 0x50, 0xd9,
	0x97, 0x44, 0x3e, 0x41, 0x77, 0xe9, 0x04, 0xc8, 0x56, 0x5c, 0xa4, 0xf1, 0x8d, 0x3f, 0x8b, 0xc1,
	0x1f, 0x65, 0x1d, 0xed, 0x7c, 0xfd, 0xf9, 0xeb, 0xdb, 0xca, 0x76, 0xd4, 0x1f, 0x55, 0x35, 0x1b,
	0xf1, 0x8a, 0x39, 0x0c, 0xf6, 0xc9, 0x18, 0x60, 0xfe, 0x3b, 0x48, 0xcf, 0x46, 0x2c, 0x9e, 0xca,
	0x60, 0x59, 0xd1, 0xd1, 0x3d, 0x97, 0xd7, 0x8f, 0x5a, 0x57, 0x79, 0xe7, 0x68, 0x0e, 0x83, 0xfd,
	0xb4, 0xe1, 0x6e, 0xf3, 0xf9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0xce, 0x33, 0xa5, 0x1d,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	InitiatePayment(ctx context.Context, in *InitiatePaymentRq, opts ...grpc.CallOption) (*InitiatePaymentRs, error)
	GetPayment(ctx context.Context, in *GetPaymentRq, opts ...grpc.CallOption) (*GetPaymentRs, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) InitiatePayment(ctx context.Context, in *InitiatePaymentRq, opts ...grpc.CallOption) (*InitiatePaymentRs, error) {
	out := new(InitiatePaymentRs)
	err := c.cc.Invoke(ctx, "/pb.PaymentService/InitiatePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPayment(ctx context.Context, in *GetPaymentRq, opts ...grpc.CallOption) (*GetPaymentRs, error) {
	out := new(GetPaymentRs)
	err := c.cc.Invoke(ctx, "/pb.PaymentService/GetPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	InitiatePayment(context.Context, *InitiatePaymentRq) (*InitiatePaymentRs, error)
	GetPayment(context.Context, *GetPaymentRq) (*GetPaymentRs, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) InitiatePayment(ctx context.Context, req *InitiatePaymentRq) (*InitiatePaymentRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiatePayment not implemented")
}
func (*UnimplementedPaymentServiceServer) GetPayment(ctx context.Context, req *GetPaymentRq) (*GetPaymentRs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayment not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_InitiatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiatePaymentRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).InitiatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PaymentService/InitiatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).InitiatePayment(ctx, req.(*InitiatePaymentRq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PaymentService/GetPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPayment(ctx, req.(*GetPaymentRq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiatePayment",
			Handler:    _PaymentService_InitiatePayment_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _PaymentService_GetPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
