// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PaymentRequest struct {
	ApplicationId    string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	MerchantId       string `protobuf:"bytes,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	SubApplicationId string `protobuf:"bytes,3,opt,name=sub_application_id,json=subApplicationId,proto3" json:"sub_application_id,omitempty"`
	SubMerchantId    string `protobuf:"bytes,4,opt,name=sub_merchant_id,json=subMerchantId,proto3" json:"sub_merchant_id,omitempty"`
	DeviceId         string `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Unique transaction reference id, random string of 32
	TransactionRefId string `protobuf:"bytes,6,opt,name=transaction_ref_id,json=transactionRefId,proto3" json:"transaction_ref_id,omitempty"`
	Description      string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Version          string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	// Json data serialized (blob)
	ItemDetails string `protobuf:"bytes,9,opt,name=item_details,json=itemDetails,proto3" json:"item_details,omitempty"`
	// Json data serialized (blob)
	InvoiceDetails      string `protobuf:"bytes,10,opt,name=invoice_details,json=invoiceDetails,proto3" json:"invoice_details,omitempty"`
	AddtionalData       string `protobuf:"bytes,11,opt,name=addtional_data,json=addtionalData,proto3" json:"addtional_data,omitempty"`
	MerchantOrderNumber string `protobuf:"bytes,12,opt,name=merchant_order_number,json=merchantOrderNumber,proto3" json:"merchant_order_number,omitempty"`
	PaymentAmount       int64  `protobuf:"varint,13,opt,name=payment_amount,json=paymentAmount,proto3" json:"payment_amount,omitempty"`
	CurrencyCode        string `protobuf:"bytes,14,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	TerminalIpAddress   string `protobuf:"bytes,15,opt,name=terminal_ip_address,json=terminalIpAddress,proto3" json:"terminal_ip_address,omitempty"`
	// Bar code/QR code
	AuthorizationCode string `protobuf:"bytes,16,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	// payment request will be valid (usable) between start_time and
	// end_time set in UTC. Attempts to use a user payment option to make a
	// booking outside of this interval will fail. (both optional)
	ValidStartTime       *timestamp.Timestamp `protobuf:"bytes,17,opt,name=valid_start_time,json=validStartTime,proto3" json:"valid_start_time,omitempty"`
	ValidEndTime         *timestamp.Timestamp `protobuf:"bytes,18,opt,name=valid_end_time,json=validEndTime,proto3" json:"valid_end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetApplicationId() string {
	if m != nil {
		return m.ApplicationId
	}
	return ""
}

func (m *PaymentRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *PaymentRequest) GetSubApplicationId() string {
	if m != nil {
		return m.SubApplicationId
	}
	return ""
}

func (m *PaymentRequest) GetSubMerchantId() string {
	if m != nil {
		return m.SubMerchantId
	}
	return ""
}

func (m *PaymentRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *PaymentRequest) GetTransactionRefId() string {
	if m != nil {
		return m.TransactionRefId
	}
	return ""
}

func (m *PaymentRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PaymentRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PaymentRequest) GetItemDetails() string {
	if m != nil {
		return m.ItemDetails
	}
	return ""
}

func (m *PaymentRequest) GetInvoiceDetails() string {
	if m != nil {
		return m.InvoiceDetails
	}
	return ""
}

func (m *PaymentRequest) GetAddtionalData() string {
	if m != nil {
		return m.AddtionalData
	}
	return ""
}

func (m *PaymentRequest) GetMerchantOrderNumber() string {
	if m != nil {
		return m.MerchantOrderNumber
	}
	return ""
}

func (m *PaymentRequest) GetPaymentAmount() int64 {
	if m != nil {
		return m.PaymentAmount
	}
	return 0
}

func (m *PaymentRequest) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *PaymentRequest) GetTerminalIpAddress() string {
	if m != nil {
		return m.TerminalIpAddress
	}
	return ""
}

func (m *PaymentRequest) GetAuthorizationCode() string {
	if m != nil {
		return m.AuthorizationCode
	}
	return ""
}

func (m *PaymentRequest) GetValidStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.ValidStartTime
	}
	return nil
}

func (m *PaymentRequest) GetValidEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.ValidEndTime
	}
	return nil
}

type PaymentResponse struct {
	TransactionRefId     string   `protobuf:"bytes,1,opt,name=transaction_ref_id,json=transactionRefId,proto3" json:"transaction_ref_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentResponse) Reset()         { *m = PaymentResponse{} }
func (m *PaymentResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentResponse) ProtoMessage()    {}
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *PaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentResponse.Unmarshal(m, b)
}
func (m *PaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentResponse.Marshal(b, m, deterministic)
}
func (m *PaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentResponse.Merge(m, src)
}
func (m *PaymentResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentResponse.Size(m)
}
func (m *PaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentResponse proto.InternalMessageInfo

func (m *PaymentResponse) GetTransactionRefId() string {
	if m != nil {
		return m.TransactionRefId
	}
	return ""
}

func (m *PaymentResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentRequest)(nil), "pb.PaymentRequest")
	proto.RegisterType((*PaymentResponse)(nil), "pb.PaymentResponse")
}

func init() { proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410) }

var fileDescriptor_6362648dfa63d410 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcd, 0x6e, 0x13, 0x3f,
	0x14, 0xc5, 0x35, 0xed, 0xff, 0x9f, 0x36, 0xce, 0x67, 0x1d, 0x15, 0x8d, 0x52, 0xa4, 0x86, 0x20,
	0x20, 0x42, 0x30, 0x91, 0xc2, 0x8e, 0x15, 0x11, 0x61, 0x91, 0x05, 0x1f, 0x4a, 0x91, 0xba, 0x1c,
	0x79, 0xc6, 0x37, 0xad, 0xa5, 0x8c, 0x6d, 0xec, 0x3b, 0x91, 0xca, 0x92, 0x17, 0x60, 0xc1, 0xa3,
	0xf1, 0x0a, 0x3c, 0x08, 0xb2, 0x3d, 0x13, 0x12, 0xa4, 0x8a, 0xe5, 0x9c, 0xf3, 0xf3, 0xb9, 0x1e,
	0xfb, 0x98, 0x74, 0x34, 0xbb, 0x2b, 0x40, 0x62, 0xa2, 0x8d, 0x42, 0x45, 0x8f, 0x74, 0x36, 0xbc,
	0xbc, 0x51, 0xea, 0x66, 0x03, 0x53, 0xaf, 0x64, 0xe5, 0x7a, 0x8a, 0xa2, 0x00, 0x8b, 0xac, 0xd0,
	0x01, 0x1a, 0x3e, 0xac, 0x00, 0xa6, 0xc5, 0x94, 0x49, 0xa9, 0x90, 0xa1, 0x50, 0xd2, 0x06, 0x77,
	0xfc, 0xbd, 0x41, 0xba, 0x9f, 0x42, 0xe8, 0x0a, 0xbe, 0x94, 0x60, 0x91, 0x3e, 0x21, 0x5d, 0xa6,
	0xf5, 0x46, 0xe4, 0x1e, 0x4c, 0x05, 0x8f, 0xa3, 0x51, 0x34, 0x69, 0xae, 0x3a, 0x7b, 0xea, 0x92,
	0xd3, 0x4b, 0xd2, 0x2a, 0xc0, 0xe4, 0xb7, 0x4c, 0xa2, 0x63, 0x8e, 0x3c, 0x43, 0x6a, 0x69, 0xc9,
	0xe9, 0x0b, 0x42, 0x6d, 0x99, 0xa5, 0x7f, 0x65, 0x1d, 0x7b, 0xae, 0x6f, 0xcb, 0x6c, 0x7e, 0x10,
	0xf7, 0x94, 0xf4, 0x1c, 0xbd, 0x1f, 0xf9, 0x5f, 0x18, 0x6b, 0xcb, 0xec, 0xfd, 0x9f, 0xd4, 0x0b,
	0xd2, 0xe4, 0xb0, 0x15, 0x39, 0x38, 0xe2, 0x7f, 0x4f, 0x9c, 0x06, 0x21, 0x8c, 0x44, 0xc3, 0xa4,
	0x65, 0xb9, 0x1f, 0x67, 0x60, 0xed, 0xa8, 0x46, 0x18, 0xb9, 0xe7, 0xac, 0x60, 0xbd, 0xe4, 0x74,
	0x44, 0x5a, 0x1c, 0x6c, 0x6e, 0x84, 0x76, 0x5a, 0x7c, 0xe2, 0xb1, 0x7d, 0x89, 0xc6, 0xe4, 0x64,
	0x0b, 0xc6, 0x3a, 0xf7, 0xd4, 0xbb, 0xf5, 0x27, 0x7d, 0x44, 0xda, 0x02, 0xa1, 0x48, 0x39, 0x20,
	0x13, 0x1b, 0x1b, 0x37, 0xc3, 0x62, 0xa7, 0x2d, 0x82, 0x44, 0x9f, 0x91, 0x9e, 0x90, 0x5b, 0xe5,
	0xb6, 0x5a, 0x53, 0xc4, 0x53, 0xdd, 0x4a, 0xae, 0x41, 0x77, 0xe0, 0x9c, 0xbb, 0x81, 0x6c, 0x93,
	0x72, 0x86, 0x2c, 0x6e, 0x55, 0x07, 0x5e, 0xab, 0x0b, 0x86, 0x8c, 0xce, 0xc8, 0xf9, 0xee, 0x74,
	0x94, 0xe1, 0x60, 0x52, 0x59, 0x16, 0x19, 0x98, 0xb8, 0xed, 0xe9, 0x41, 0x6d, 0x7e, 0x74, 0xde,
	0x07, 0x6f, 0xb9, 0xe8, 0xaa, 0x32, 0x29, 0x2b, 0x54, 0x29, 0x31, 0xee, 0x8c, 0xa2, 0xc9, 0xf1,
	0xaa, 0x2e, 0xd2, 0xdc, 0x8b, 0xf4, 0x31, 0xe9, 0xe4, 0xa5, 0x31, 0x20, 0xf3, 0xbb, 0x34, 0x57,
	0x1c, 0xe2, 0xae, 0x8f, 0x6c, 0xd7, 0xe2, 0x5b, 0xc5, 0x81, 0x26, 0x64, 0x80, 0x60, 0x0a, 0xe1,
	0x76, 0x29, 0x74, 0xca, 0x38, 0x37, 0x60, 0x6d, 0xdc, 0xf3, 0xe8, 0x59, 0x6d, 0x2d, 0xf5, 0x3c,
	0x18, 0xf4, 0x25, 0xa1, 0xac, 0xc4, 0x5b, 0x65, 0xc4, 0xd7, 0x70, 0xfb, 0x3e, 0xb9, 0x1f, 0xf0,
	0x03, 0xc7, 0xc7, 0x2f, 0x48, 0x7f, 0xcb, 0x36, 0x82, 0xa7, 0x16, 0x99, 0xc1, 0xd4, 0xd5, 0x38,
	0x3e, 0x1b, 0x45, 0x93, 0xd6, 0x6c, 0x98, 0x84, 0x0a, 0x27, 0x75, 0xc7, 0x93, 0xcf, 0x75, 0xc7,
	0x57, 0x5d, 0xbf, 0xe6, 0xca, 0x2d, 0x71, 0x22, 0x7d, 0x43, 0x82, 0x92, 0x82, 0xe4, 0x21, 0x83,
	0xfe, 0x33, 0xa3, 0xed, 0x57, 0xbc, 0x93, 0xdc, 0x49, 0xe3, 0x6b, 0xd2, 0xdb, 0x3d, 0x08, 0xab,
	0x95, 0xb4, 0x70, 0x4f, 0xad, 0xa2, 0x7b, 0x6a, 0xf5, 0x80, 0x34, 0x2c, 0x32, 0x2c, 0x6d, 0xf5,
	0x26, 0xaa, 0xaf, 0x99, 0xd8, 0xbd, 0xb4, 0x2b, 0x30, 0xae, 0xb0, 0xf4, 0x9a, 0xf4, 0x96, 0x52,
	0xa0, 0x60, 0x08, 0x95, 0x43, 0x69, 0xa2, 0xb3, 0xe4, 0xf0, 0x41, 0x0e, 0x07, 0x07, 0x5a, 0xd8,
	0xd3, 0xf8, 0xe2, 0xdb, 0xcf, 0x5f, 0x3f, 0x8e, 0xce, 0xc7, 0xfd, 0x69, 0x75, 0x95, 0x53, 0x21,
	0x05, 0x32, 0x84, 0xd7, 0xd1, 0xf3, 0xac, 0xe1, 0xff, 0xf2, 0xd5, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0x9d, 0xaf, 0xaa, 0x30, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	InitiatePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) InitiatePayment(ctx context.Context, in *PaymentRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, "/pb.PaymentService/InitiatePayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	InitiatePayment(context.Context, *PaymentRequest) (*PaymentResponse, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) InitiatePayment(ctx context.Context, req *PaymentRequest) (*PaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiatePayment not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_InitiatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).InitiatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PaymentService/InitiatePayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).InitiatePayment(ctx, req.(*PaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiatePayment",
			Handler:    _PaymentService_InitiatePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
