// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: bah00100102.proto

package bah001

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// define the regex for a UUID once up-front
var _bah_00100102_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on MxBah00100102 with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MxBah00100102) Validate() error {
	if m == nil {
		return nil
	}

	if err := m._validateUuid(m.GetMsgId()); err != nil {
		return MxBah00100102ValidationError{
			field:  "MsgId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
	}

	if m.GetCreatedTimestamp() == nil {
		return MxBah00100102ValidationError{
			field:  "CreatedTimestamp",
			reason: "value is required",
		}
	}

	if l := len(m.GetFrom()); l < 1 || l > 35 {
		return MxBah00100102ValidationError{
			field:  "From",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if l := len(m.GetTo()); l < 1 || l > 35 {
		return MxBah00100102ValidationError{
			field:  "To",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if l := len(m.GetFunctionCode()); l < 1 || l > 35 {
		return MxBah00100102ValidationError{
			field:  "FunctionCode",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if l := len(m.GetBusinessService()); l < 1 || l > 35 {
		return MxBah00100102ValidationError{
			field:  "BusinessService",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	// no validation rules for Signature

	return nil
}

func (m *MxBah00100102) _validateUuid(uuid string) error {
	if matched := _bah_00100102_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// MxBah00100102ValidationError is the validation error returned by
// MxBah00100102.Validate if the designated constraints aren't met.
type MxBah00100102ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MxBah00100102ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MxBah00100102ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MxBah00100102ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MxBah00100102ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MxBah00100102ValidationError) ErrorName() string { return "MxBah00100102ValidationError" }

// Error satisfies the builtin error interface
func (e MxBah00100102ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMxBah00100102.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MxBah00100102ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MxBah00100102ValidationError{}
