version: '3.7'
services:
  payhub:
    environment: 
        - APP_NAME=payhub
        - APP_PORT=9000
        - BUILD_ENV=development
        - LOG_LEVEL=debug
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        build_env: 'development'
        app_port: 9000
        protobuf_release_tag: '3.17.3'
    ports:
      - "19000:9000"
      - "19001:9001"    
