// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/common.proto

package common

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// define the regex for a UUID once up-front
var _common_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Id with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Id) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetOrgId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IdValidationError{
				field:  "OrgId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// IdValidationError is the validation error returned by Id.Validate if the
// designated constraints aren't met.
type IdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdValidationError) ErrorName() string { return "IdValidationError" }

// Error satisfies the builtin error interface
func (e IdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdValidationError{}

// Validate checks the field values on OrgId with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *OrgId) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetOthr()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrgIdValidationError{
				field:  "Othr",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// OrgIdValidationError is the validation error returned by OrgId.Validate if
// the designated constraints aren't met.
type OrgIdValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrgIdValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrgIdValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrgIdValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrgIdValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrgIdValidationError) ErrorName() string { return "OrgIdValidationError" }

// Error satisfies the builtin error interface
func (e OrgIdValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrgId.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrgIdValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrgIdValidationError{}

// Validate checks the field values on Othr with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Othr) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	return nil
}

// OthrValidationError is the validation error returned by Othr.Validate if the
// designated constraints aren't met.
type OthrValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OthrValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OthrValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OthrValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OthrValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OthrValidationError) ErrorName() string { return "OthrValidationError" }

// Error satisfies the builtin error interface
func (e OthrValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOthr.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OthrValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OthrValidationError{}

// Validate checks the field values on InitiatingParty with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *InitiatingParty) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InitiatingPartyValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// InitiatingPartyValidationError is the validation error returned by
// InitiatingParty.Validate if the designated constraints aren't met.
type InitiatingPartyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitiatingPartyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitiatingPartyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitiatingPartyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitiatingPartyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitiatingPartyValidationError) ErrorName() string { return "InitiatingPartyValidationError" }

// Error satisfies the builtin error interface
func (e InitiatingPartyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitiatingParty.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitiatingPartyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitiatingPartyValidationError{}

// Validate checks the field values on Money with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Money) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for CurrencyCode

	// no validation rules for Value

	return nil
}

// MoneyValidationError is the validation error returned by Money.Validate if
// the designated constraints aren't met.
type MoneyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MoneyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MoneyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MoneyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MoneyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MoneyValidationError) ErrorName() string { return "MoneyValidationError" }

// Error satisfies the builtin error interface
func (e MoneyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMoney.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MoneyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MoneyValidationError{}

// Validate checks the field values on PaymentIdentification with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PaymentIdentification) Validate() error {
	if m == nil {
		return nil
	}

	if err := m._validateUuid(m.GetEndToEndId()); err != nil {
		return PaymentIdentificationValidationError{
			field:  "EndToEndId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
	}

	if l := len(m.GetTransactionId()); l < 1 || l > 36 {
		return PaymentIdentificationValidationError{
			field:  "TransactionId",
			reason: "value length must be between 1 and 36 bytes, inclusive",
		}
	}

	if err := m._validateUuid(m.GetUetr()); err != nil {
		return PaymentIdentificationValidationError{
			field:  "Uetr",
			reason: "value must be a valid UUID",
			cause:  err,
		}
	}

	return nil
}

func (m *PaymentIdentification) _validateUuid(uuid string) error {
	if matched := _common_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PaymentIdentificationValidationError is the validation error returned by
// PaymentIdentification.Validate if the designated constraints aren't met.
type PaymentIdentificationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentIdentificationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentIdentificationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentIdentificationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentIdentificationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentIdentificationValidationError) ErrorName() string {
	return "PaymentIdentificationValidationError"
}

// Error satisfies the builtin error interface
func (e PaymentIdentificationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentIdentification.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentIdentificationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentIdentificationValidationError{}

// Validate checks the field values on PaymentTypeInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PaymentTypeInformation) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ServiceLevel

	// no validation rules for LocalInstrument

	// no validation rules for PaymentChannel

	return nil
}

// PaymentTypeInformationValidationError is the validation error returned by
// PaymentTypeInformation.Validate if the designated constraints aren't met.
type PaymentTypeInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PaymentTypeInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PaymentTypeInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PaymentTypeInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PaymentTypeInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PaymentTypeInformationValidationError) ErrorName() string {
	return "PaymentTypeInformationValidationError"
}

// Error satisfies the builtin error interface
func (e PaymentTypeInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPaymentTypeInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PaymentTypeInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PaymentTypeInformationValidationError{}
