// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pacs00800110.proto

package pacs008

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// define the regex for a UUID once up-front
var _pacs_00800110_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on DebitInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *DebitInfo) Validate() error {
	if m == nil {
		return nil
	}

	if l := len(m.GetAccountId()); l < 1 || l > 35 {
		return DebitInfoValidationError{
			field:  "AccountId",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if l := len(m.GetFinInstId()); l < 1 || l > 35 {
		return DebitInfoValidationError{
			field:  "FinInstId",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if l := len(m.GetName()); l < 1 || l > 35 {
		return DebitInfoValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if m.GetAmount() == nil {
		return DebitInfoValidationError{
			field:  "Amount",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DebitInfoValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Tags

	return nil
}

// DebitInfoValidationError is the validation error returned by
// DebitInfo.Validate if the designated constraints aren't met.
type DebitInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DebitInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DebitInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DebitInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DebitInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DebitInfoValidationError) ErrorName() string { return "DebitInfoValidationError" }

// Error satisfies the builtin error interface
func (e DebitInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDebitInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DebitInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DebitInfoValidationError{}

// Validate checks the field values on CreditInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *CreditInfo) Validate() error {
	if m == nil {
		return nil
	}

	if l := len(m.GetAccountId()); l < 1 || l > 35 {
		return CreditInfoValidationError{
			field:  "AccountId",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if l := len(m.GetFinInstId()); l < 1 || l > 35 {
		return CreditInfoValidationError{
			field:  "FinInstId",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if l := len(m.GetName()); l < 1 || l > 35 {
		return CreditInfoValidationError{
			field:  "Name",
			reason: "value length must be between 1 and 35 bytes, inclusive",
		}
	}

	if m.GetAmount() == nil {
		return CreditInfoValidationError{
			field:  "Amount",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreditInfoValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Tags

	return nil
}

// CreditInfoValidationError is the validation error returned by
// CreditInfo.Validate if the designated constraints aren't met.
type CreditInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreditInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreditInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreditInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreditInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreditInfoValidationError) ErrorName() string { return "CreditInfoValidationError" }

// Error satisfies the builtin error interface
func (e CreditInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreditInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreditInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreditInfoValidationError{}

// Validate checks the field values on GroupHeader with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *GroupHeader) Validate() error {
	if m == nil {
		return nil
	}

	if err := m._validateUuid(m.GetMsgId()); err != nil {
		return GroupHeaderValidationError{
			field:  "MsgId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
	}

	if m.GetCreatedDatetime() == nil {
		return GroupHeaderValidationError{
			field:  "CreatedDatetime",
			reason: "value is required",
		}
	}

	// no validation rules for NumberOfTxns

	if v, ok := interface{}(m.GetTotalSettlementAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GroupHeaderValidationError{
				field:  "TotalSettlementAmount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SettlementMethod

	return nil
}

func (m *GroupHeader) _validateUuid(uuid string) error {
	if matched := _pacs_00800110_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GroupHeaderValidationError is the validation error returned by
// GroupHeader.Validate if the designated constraints aren't met.
type GroupHeaderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GroupHeaderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GroupHeaderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GroupHeaderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GroupHeaderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GroupHeaderValidationError) ErrorName() string { return "GroupHeaderValidationError" }

// Error satisfies the builtin error interface
func (e GroupHeaderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGroupHeader.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GroupHeaderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GroupHeaderValidationError{}

// Validate checks the field values on CreditTransferInformation with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *CreditTransferInformation) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetGroupHeader()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreditTransferInformationValidationError{
				field:  "GroupHeader",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetPaymentId() == nil {
		return CreditTransferInformationValidationError{
			field:  "PaymentId",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetPaymentId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreditTransferInformationValidationError{
				field:  "PaymentId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetPaymentType() == nil {
		return CreditTransferInformationValidationError{
			field:  "PaymentType",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetPaymentType()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreditTransferInformationValidationError{
				field:  "PaymentType",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetSettlementAmount() == nil {
		return CreditTransferInformationValidationError{
			field:  "SettlementAmount",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetSettlementAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreditTransferInformationValidationError{
				field:  "SettlementAmount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetDebitInfo() == nil {
		return CreditTransferInformationValidationError{
			field:  "DebitInfo",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetDebitInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreditTransferInformationValidationError{
				field:  "DebitInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(m.GetCreditInfo()) < 1 {
		return CreditTransferInformationValidationError{
			field:  "CreditInfo",
			reason: "value must contain at least 1 item(s)",
		}
	}

	for idx, item := range m.GetCreditInfo() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CreditTransferInformationValidationError{
					field:  fmt.Sprintf("CreditInfo[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// CreditTransferInformationValidationError is the validation error returned by
// CreditTransferInformation.Validate if the designated constraints aren't met.
type CreditTransferInformationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreditTransferInformationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreditTransferInformationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreditTransferInformationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreditTransferInformationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreditTransferInformationValidationError) ErrorName() string {
	return "CreditTransferInformationValidationError"
}

// Error satisfies the builtin error interface
func (e CreditTransferInformationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreditTransferInformation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreditTransferInformationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreditTransferInformationValidationError{}

// Validate checks the field values on MxPacs00800110 with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MxPacs00800110) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetHeader() == nil {
		return MxPacs00800110ValidationError{
			field:  "Header",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetHeader()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MxPacs00800110ValidationError{
				field:  "Header",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetBody() == nil {
		return MxPacs00800110ValidationError{
			field:  "Body",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetBody()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MxPacs00800110ValidationError{
				field:  "Body",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// MxPacs00800110ValidationError is the validation error returned by
// MxPacs00800110.Validate if the designated constraints aren't met.
type MxPacs00800110ValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MxPacs00800110ValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MxPacs00800110ValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MxPacs00800110ValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MxPacs00800110ValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MxPacs00800110ValidationError) ErrorName() string { return "MxPacs00800110ValidationError" }

// Error satisfies the builtin error interface
func (e MxPacs00800110ValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMxPacs00800110.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MxPacs00800110ValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MxPacs00800110ValidationError{}
